DROP TABLE DIM_PRODUTO CASCADE CONSTRAINTS;
CREATE TABLE LUCASJ.DIM_PRODUTO (
    COD_PRODUTO         NUMBER(6),
    DESCRICAO_PRODUTO   VARCHAR2(50 BYTE),
    PRECO_BASE          NUMBER(10,2),
    QTD_ESTOQUE         NUMBER(4),
    NOME_GRUPO          VARCHAR2(50 BYTE),
    IPI_GRUPO           NUMBER(7, 2),
    PRIMARY KEY (COD_PRODUTO)
);

DROP TABLE DIM_CLIENTE CASCADE CONSTRAINTS;
CREATE TABLE DIM_CLIENTE (
    CPF                 NUMBER(11),
    NOME_CLIENTE        VARCHAR2(50 BYTE),
    PRIMARY KEY (CPF)
);

DROP TABLE DIM_VENDEDOR CASCADE CONSTRAINTS;
CREATE TABLE DIM_VENDEDOR (
    COD_VENDEDOR        NUMBER(11),
    NOME_VENDEDOR       VARCHAR2(50 BYTE),
    PRIMARY KEY (COD_VENDEDOR)
);

DROP TABLE DIM_TEMPO CASCADE CONSTRAINTS;
CREATE TABLE DIM_TEMPO (
    ID_TEMPO            NUMBER(6),
    NU_MES              NUMBER(2),
    NU_ANO              NUMBER(4),
    NU_BIMESTRE         NUMBER(1),
    NU_TRIMESTRE        NUMBER(1),
    DE_MES              VARCHAR2(20 BYTE),
    DE_TRIMESTRE        VARCHAR2(5 BYTE),
    PRIMARY KEY (ID_TEMPO)
);


DROP TABLE FATO_VENDAS CASCADE CONSTRAINTS;
CREATE TABLE FATO_VENDAS (
    COD_PRODUTO         NUMBER(6),
    COD_VENDEDOR        NUMBER(11),
    CPF         NUMBER(11),
    ID_TEMPO           NUMBER(6),
    QTD_VENDIDA         NUMBER(6),
    VALOR_VENDA         NUMBER(10, 2),
    FOREIGN KEY (COD_PRODUTO) REFERENCES DIM_PRODUTO (COD_PRODUTO),
    FOREIGN KEY (CPF) REFERENCES DIM_CLIENTE (CPF),
    FOREIGN KEY (COD_VENDEDOR) REFERENCES DIM_VENDEDOR (COD_VENDEDOR),
    FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO (ID_TEMPO)
);