-- Exercise a __________________________________
SELECT MAX(FATO_VENDAS.QTD_VENDIDA) as MAX_VENDAS, NU_TRIMESTRE as TRIMESTRE_2017 -- , DIM_PRODUTO.DESCRICAO_PRODUTO
FROM DIM_PRODUTO JOIN FATO_VENDAS
ON DIM_PRODUTO.COD_PRODUTO = FATO_VENDAS.COD_PRODUTO
JOIN DIM_TEMPO
ON DIM_TEMPO.ID_TEMPO = FATO_VENDAS.ID_TEMPO
WHERE DIM_TEMPO.NU_ANO = '2017'
GROUP BY NU_TRIMESTRE;
    
SELECT MAX(FATO_VENDAS.QTD_VENDIDA) as MAX_VENDAS, NU_TRIMESTRE as TRIMESTRE_2018 -- , DIM_PRODUTO.DESCRICAO_PRODUTO
FROM DIM_PRODUTO JOIN FATO_VENDAS
ON DIM_PRODUTO.COD_PRODUTO = FATO_VENDAS.COD_PRODUTO
JOIN DIM_TEMPO
ON DIM_TEMPO.ID_TEMPO = FATO_VENDAS.ID_TEMPO
WHERE DIM_TEMPO.NU_ANO = '2018'
GROUP BY NU_TRIMESTRE;


-- Exercise b __________________________________
WITH SUBQUERY AS (
        SELECT SUM(FATO_VENDAS.VALOR_VENDA) AS FATURAMENTO_2017, DIM_CLIENTE.CPF AS CPF
        FROM FATO_VENDAS JOIN DIM_CLIENTE
        ON FATO_VENDAS.CPF = DIM_CLIENTE.CPF
        JOIN DIM_TEMPO
        ON DIM_TEMPO.ID_TEMPO = FATO_VENDAS.ID_TEMPO
        WHERE DIM_TEMPO.NU_ANO = '2017'
        GROUP BY DIM_CLIENTE.CPF
        )
SELECT QUERY_B.*
FROM
    (
    SELECT FATURAMENTO_2017, NOME_CLIENTE
    FROM SUBQUERY
    JOIN DIM_CLIENTE
    ON SUBQUERY.CPF = DIM_CLIENTE.CPF
    ORDER BY FATURAMENTO_2017 DESC
    ) QUERY_B
WHERE ROWNUM = 1;

WITH SUBQUERY AS (
        SELECT SUM(FATO_VENDAS.VALOR_VENDA) AS FATURAMENTO_2018, DIM_CLIENTE.CPF AS CPF
        FROM FATO_VENDAS JOIN DIM_CLIENTE
        ON FATO_VENDAS.CPF = DIM_CLIENTE.CPF
        JOIN DIM_TEMPO
        ON DIM_TEMPO.ID_TEMPO = FATO_VENDAS.ID_TEMPO
        WHERE DIM_TEMPO.NU_ANO = '2018'
        GROUP BY DIM_CLIENTE.CPF
        )
SELECT QUERY_B.*
FROM
    (
    SELECT FATURAMENTO_2018, NOME_CLIENTE
    FROM SUBQUERY
    JOIN DIM_CLIENTE
    ON SUBQUERY.CPF = DIM_CLIENTE.CPF
    ORDER BY FATURAMENTO_2018 DESC
    ) QUERY_B
WHERE ROWNUM = 1;


-- Exercise c __________________________________
SELECT DIM_VENDEDOR.NOME_VENDEDOR, DIM_PRODUTO.DESCRICAO_PRODUTO AS PRODUTO_2017, FATO_VENDAS.QTD_VENDIDA
FROM FATO_VENDAS
JOIN DIM_TEMPO
ON FATO_VENDAS.ID_TEMPO = DIM_TEMPO.ID_TEMPO
JOIN DIM_VENDEDOR
ON DIM_VENDEDOR.COD_VENDEDOR = FATO_VENDAS.COD_VENDEDOR
JOIN DIM_PRODUTO
ON DIM_PRODUTO.COD_PRODUTO = FATO_VENDAS.COD_PRODUTO
WHERE DIM_TEMPO.NU_ANO = '2017'
ORDER BY DIM_VENDEDOR.NOME_VENDEDOR ASC;

SELECT DIM_VENDEDOR.NOME_VENDEDOR, DIM_PRODUTO.DESCRICAO_PRODUTO AS PRODUTO_2018, FATO_VENDAS.QTD_VENDIDA
FROM FATO_VENDAS
JOIN DIM_TEMPO
ON FATO_VENDAS.ID_TEMPO = DIM_TEMPO.ID_TEMPO
JOIN DIM_VENDEDOR
ON DIM_VENDEDOR.COD_VENDEDOR = FATO_VENDAS.COD_VENDEDOR
JOIN DIM_PRODUTO
ON DIM_PRODUTO.COD_PRODUTO = FATO_VENDAS.COD_PRODUTO
WHERE DIM_TEMPO.NU_ANO = '2018'
ORDER BY DIM_VENDEDOR.NOME_VENDEDOR ASC;